servers:
    - name: server_1
      port: 4573
      endpoints:
        - url: /simple_url
          GET:
            response: '{"a": 1}'
            content_type: application/json
          POST:
            response: "OK"
            content_type: text/plain

