servers:
    - name: server_1
      port: 4573
      endpoints:
        - url: /simple_url
          GET:
            body: '{"a": 1}'
            content_type: application/json
          POST:
            body: "OK"
            content_type: text/plain
            status_code: 201

