collect_statistics: true
servers:
  - name: server_1
    port: 4573
    endpoints:
      - url: /simple_url
        GET:
          template: "{}"
          headers:
            content-type: application/json
        POST:
          template: "OK"
          status_code: 201
          headers:
            content-type: text/plain
      - url: /picture
        GET:
          file: file://mimicro.png
      - url: /{var}/in/filepath
        GET:
          file: file://{{.var}}micro.png
      - url: /template_from_file/{var}
        PUT:
          template: file://response_with_var.json
          headers:
            content-type: application/json
      - url: /string_template/{var}
        DELETE:
          template: "var is {{.var}}"
          status_code: 403
