collect_statistics: true
servers:
  - name: server_1
    port: 4573
    endpoints:
      - url: /simple_url
        GET:
          template: "{}"
          content_type: application/json
        POST:
          template: "OK"
          content_type: text/plain
          status_code: 201
      - url: /picture
        GET:
          file: file://mimicro.png
      - url: /url/with/{var}
        GET:
          template: file://response_with_var.json
          content_type: application/json
